version: '3.8'

services:
  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    ports:
      - "5432:5432"

  django:
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./.env.prod
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: null
  static_volume: null
