version: '3.8'

services:
  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    ports:
      - "5433:5432"

  django:
    restart: always
    volumes:
      - ./:/app:cached
    build: ./
    env_file:
      - ./.env.prod
    ports:
      - "8090:8080"
    depends_on:
      - db

volumes:
  postgres_data: null
