# Generated by Django 4.0 on 2021-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='draw_date',
            field=models.DateField(verbose_name='Дата жеребьёвки'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gift_date',
            field=models.DateField(verbose_name='Дата отправки подарка'),
        ),
        migrations.AlterField(
            model_name='santa',
            name='game',
            field=models.ManyToManyField(blank=True, related_name='santas', to='games.Game', verbose_name='игра'),
        ),
        migrations.AlterField(
            model_name='santa',
            name='letter_to_santa',
            field=models.TextField(blank=True, null=True, verbose_name='Письмо Санте'),
        ),
        migrations.AlterField(
            model_name='santa',
            name='wishlist',
            field=models.TextField(blank=True, null=True, verbose_name='Желания'),
        ),
    ]
