# Generated by Django 4.0 on 2021-12-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_draw_date_alter_game_gift_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exclusions', to='games.game', verbose_name='игра')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='givers_to_exclude', to='games.santa', verbose_name='даритель')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivers_to_eclude', to='games.santa', verbose_name='одаряемый')),
            ],
            options={
                'verbose_name': 'пара-исключение',
                'verbose_name_plural': 'пары-исключения',
            },
        ),
    ]
