# Generated by Django 4.0 on 2021-12-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='santa',
            old_name='game',
            new_name='games',
        ),
    ]
