# Generated by Django 4.0 on 2021-12-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='santa', to='games.customuser'),
        ),
    ]
