# Generated by Django 4.0 on 2021-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_santa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(null=True, verbose_name='урл'),
        ),
    ]
