# Generated by Django 4.0 on 2021-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='урл'),
        ),
    ]
